export const SIGN_UP_REQUEST = 'SIGN_UP_REQUEST'
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS'
export const SIGN_UP_FAILURE = 'SIGN_UP_SUCCESS'

export const LOG_OUT = 'LOG_OUT'
export const LOG_IN = 'LOG_IN'

export const LOG_IN_REQUEST = 'LOG_IN_REQUEST'
export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS'
export const LOG_IN_FAILURE = 'LOG_IN_FAILURE'

export const LOAD_SETTINGS_REQUEST = 'LOAD_SETTINGS_REQUEST'
export const LOAD_SETTINGS_SUCCESS = 'LOAD_SETTINGS_SUCCESS'
export const LOAD_SETTINGS_FAILURE = 'LOAD_SETTINGS_FAILURE'

export const SAVE_SETTINGS_REQUEST = 'SAVE_SETTINGS_REQUEST'
export const SAVE_SETTINGS_SUCCESS = 'SAVE_SETTINGS_SUCCESS'
export const SAVE_SETTINGS_FAILURE = 'SAVE_SETTINGS_FAILURE'