
// export const LOG_OUT = 'LOG_OUT'
// export const LOG_IN = 'LOG_IN'

// export const LOG_IN_REQUEST = 'LOG_IN_REQUEST'
// export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS'
// export const LOG_IN_FAILURE = 'LOG_IN_FAILURE'

export enum signUpTypes {
	SIGN_UP_REQUEST = 'SIGN_UP_REQUEST',
	SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS',
	SIGN_UP_FAILURE = 'SIGN_UP_FAILURE'
}

export enum logInTypes {
	LOG_IN_REQUEST = 'LOG_IN_REQUEST',
	LOG_IN_SUCCESS = 'LOG_IN_SUCCESS',
	LOG_IN_FAILURE = 'LOG_IN_FAILURE'
}

export enum settingsTypes {
	LOAD_SETTINGS_REQUEST = 'LOAD_SETTINGS_REQUEST',
	LOAD_SETTINGS_SUCCESS = 'LOAD_SETTINGS_SUCCESS',
	LOAD_SETTINGS_FAILURE = 'LOAD_SETTINGS_FAILURE',
	
	SAVE_SETTINGS_REQUEST = 'SAVE_SETTINGS_REQUEST',
	SAVE_SETTINGS_SUCCESS = 'SAVE_SETTINGS_SUCCESS',
	SAVE_SETTINGS_FAILURE = 'SAVE_SETTINGS_FAILURE',
}